### ISSUE TITLE
fatal error: 'frag.spv' file not found when trying to build

### ISSUE THREAD

**Issue by kanaritech** [artyomd/Quest-XR#1]
Hi!

First of all, thanks a lot to share an open-xr demo project to use on Meta Quest 2, I've been trying to create one myself but I've not been able to.

Your project seems to gradle sync correctly when I open it with Android Studio, but when I try to either:
- Execute ./gradlew assembleDebug from the terminal
- Click the run button above

I get the following error:

Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
com.android.ide.common.process.ProcessException: ninja: Entering directory `**<my_path_to_your_project>**\Quest-XR\app\.cxx\Debug\r4y10b23\arm64-v8a'
  [1/4] Generating ../../../../../../cpp/shaders/spv/frag.spv, ../../../../../../cpp/shaders/spv/.hex/frag.spv, ../../../../../../cpp/shaders/spv/vert.spv, ../../../../../../cpp/shaders/spv/.hex/vert.spv
  [2/4] Building CXX object cpp/shaders/CMakeFiles/shaders.dir/shaders.cpp.o
  FAILED: cpp/shaders/CMakeFiles/shaders.dir/shaders.cpp.o 
  **<my_path_to_AppData>**\AppData\Local\Android\Sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android29 --sysroot=**<my_path_to_AppData>**/AppData/Local/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -I **<my_path_to_your_project>**/Quest-XR/app/cpp/shaders/spv/.hex -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -g  -fno-limit-debug-info -fPIC -std=gnu++20 -MD -MT cpp/shaders/CMakeFiles/shaders.dir/shaders.cpp.o -MF cpp\shaders\CMakeFiles\shaders.dir\shaders.cpp.o.d -o cpp/shaders/CMakeFiles/shaders.dir/shaders.cpp.o -c **<my_path_to_your_project>**/Quest-XR/app/cpp/shaders/shaders.cpp
  **<my_path_to_your_project>**/Quest-XR/app/cpp/shaders/shaders.cpp:12:10: **_fatal error: 'frag.spv' file not found_**
  #include SHADER(frag)
           ^~~~~~~~~~~~
  **<my_path_to_your_project>**/Quest-XR/app/cpp/shaders/shaders.cpp:7:25: note: expanded from macro 'SHADER'
  #define SHADER(_name_)  STRINGIFY(_name_.spv)
                          ^~~~~~~~~~~~~~~~~~~~~
  **<my_path_to_your_project>**/Quest-XR/app/cpp/shaders/shaders.cpp:6:27: note: expanded from macro 'STRINGIFY'
  #define STRINGIFY(_name_) #_name_
                            ^~~~~~~
  <scratch space>:266:1: note: expanded from here
  "frag.spv"
  ^~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

I've tried to copy the file **frag.spv** from https://github.com/KhronosGroup/OpenXR-SDK-Source/tree/main/src/tests/hello_xr/vulkan_shaders, but then it prints me another error.

Do you know what could be happening here?

Thanks again!

**Comment by artyomd** [comment]
Hey 👋  this is because the shader compilation logic was written in a bash script and I suspect you are building the project on Windows and the bash scripts are not being executed in your env. So I have just updated the project and removed the bash script and the latest version relies on the shader compiler of the android ndk. So pls give it a try and let me know. I do not have any Windows machines to test this myself. Thank you 🙌

**Comment by BattleAxeVR** [comment]
![image](https://github.com/artyomd/Quest-XR/assets/11604039/23241112-ba8f-4621-ac54-9e92f9b0d9bd)

Doesn't work unfortunately.

**Comment by adrian-afl** [comment]
I suppose you are on Windows
Go here `cpp/shaders/CMakeLists.txt`
on the first line, change
`set(glslc_exe "${CMAKE_ANDROID_NDK}/shader-tools/${CMAKE_ANDROID_NDK_TOOLCHAIN_HOST_TAG}/glslc")`
to
`set(glslc_exe "${CMAKE_ANDROID_NDK}/shader-tools/${CMAKE_ANDROID_NDK_TOOLCHAIN_HOST_TAG}/glslc.exe")`

**Comment by artyomd** [comment]
I have updated the `glsc` path to include the `TOOL_OS_SUFFIX`. This should resolve the issue. Please reopen if it persists.
Note: I lack a Windows machine to verify this fix.

**Comment by kanaritech** [comment]
Hi!

Exactly, I was on Windows!

Sorry to answer almost one year after,
thanks for the fix!!
